services:
  pgdatabase:
    image: postgres:16
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "ny_taxi"
    volumes:
      - "ny_taxi_postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
    ports:
      - "8085:80"

  # taxi_ingest:
  #   image: taxi_ingest:v001
  #   container_name: taxi_ingest
  #   depends_on:
  #     - pgdatabase 
  #   command: [
  #     "--user=root",
  #     "--password=root",
  #     "--host=pgdatabase",
  #     "--port=5432",
  #     "--db=ny_taxi",
  #     "--table-name=yellow_taxi_trips",
  #     "--year=2021",
  #     "--month=1",
  #     "--chunksize=100000"
  #   ]
  # use above or run in the cli (below)

# docker run -it \
#   --network=pipeline_default \
#   taxi_ingest:v001 \
#     --user=root \
#     --password=root \
#     --host=pgdatabase \
#     --port=5432 \
#     --db=ny_taxi \
#     --table=yellow_taxi_trips

volumes:
  ny_taxi_postgres_data:
  pgadmin_data: